# db
import sqlite3
from model import my_file_model


MY_FILES_TABLE = 'files_store'

class DataBase:
    """
    This class knows how to work with Data Base based on SQL:
     1. create (open) the DB
     2. insert
     3. read back
     4. close DB
    """
    def __init__(self, db_name: str) -> None:
        """
        create the connection, and the obj that will hold a connection to SQLite database.
        name of the data base will need to be given by user
        :param db_name: str
        """
        self.conn = sqlite3.connect(db_name) # create the connection to the sqlite3 DB        
        self.cursor = self.conn.cursor()     # init of the cursor obj (that will hold the tbl), to execute SQL queries against the sqlite3 DB 
        self.create_table()
    

    def create_table(self) -> None:
        """
        # Define SQL query to create a table named 'files_storage'. The cursor will hold the table.
        Each record in the table will have then next columns:
        1.id
        2.source file (html file) 
        3.date
        
        Each column has requirements
        exp: id must be integer type (it is Primary key for this table)
        """
        try:
            self.cursor.execute(f'''
                                    CREATE TABLE IF NOT EXISTS {MY_FILES_TABLE} (
                                    id INTEGER PRIMARY KEY,
                                    source_file TEXT NOT NULL,                                    
                                    transaction_date TEXT NOT NULL
                                )
                                ''')
            # Execute the query and commit the transaction
            self.conn.commit()
            print(f"Database {MY_FILES_TABLE} table created successfully")
        except sqlite3.Error as e:
            print(f"Creation of the Database {MY_FILES_TABLE} error: {e}")
    

    def insert(self, sourse_file: str, 
                                        transaction_date: str) -> int:
        """
        This method is for inserting new record with fields: source, date into table 'files_store'
        :return the id of the newly inserted record
        """
        try:
            self.cursor.execute(f'INSERT INTO {MY_FILES_TABLE} (source_file, transaction_date) VALUES (?, ?, ?)',(sourse_file, transaction_date))
            # commit the transaction
            self.conn.commit()
            # Fetch the autogenerated ID - the id of the newly inserted record
            return self.cursor.lastrowid
        except sqlite3.Error as e:
            print(f"Database error: {e}")
            return -1
    

    def get_all_files(self) -> list[my_file_model]:
        # execution of the query
        # query selects all records (files) from the table 'files_store'
        rows = []
        try:
            self.cursor.execute(f'SELECT * FROM {MY_FILES_TABLE}')
            # we retrieve from a table raw records - each record is a file full name and date
            rows = self.cursor.fetchall()
        except sqlite3.Error as e:
            print(f"Database error: {e}")

        my_files = []
        # we need to create the -> file obj <- from the raw record. ConverFile extractuions may fail therefore it is surrounded with try and catch
        if not rows:
            print(f"No files could be found in the table {MY_FILES_TABLE}")
        else:
            for row in rows:
                try:
                    # create file name obj from record from a table that is a raw data                    
                    # it says each raw will have: id, source,date
                    my_file = my_file_model(id=row[0],
                                            source=row[1],                                           
                                            date=row[3])
                    # store the records as a conversion objects
                    my_files.append(my_file)
                except Exception as e:
                    print(f"Error creating file object: {e}")
        return my_files
    

    def get_file_by_id(self, id: int) -> my_file_model:
        """
        This method receives id of the record in the table "conversions" and retrieves a record conversion
        retrieve can fail if id isnt in the table
        :param id: an id of the desired record conversion
        :return: a record conversion
        """
        entity = None
        try:
            self.cursor.execute(f'SELECT * FROM conversions WHERE id={id}') # also possible to use f string this way: id={0}', (id,))
            # raw data, to be converted into conversion obj
            entity = self.cursor.fetchone()
            if not entity:
                return None
        except sqlite3.Error as e:
            print(f"Database error: {e}")

        conversion = None
        try:
            # conversion from raw to conversion obj - here we do it for single record
            my_file = my_file_model( id=entity[0],
                                     source=entity[1],                                    
                                     date=entity[3])
        except Exception as e:
            print(f"Error creating file object: {e}")
        finally:
            return my_file
        

    def close(self) -> None:
        """
        Closing the connection to resources
        :return: None
        """
        try:
            self.conn.close()
        except sqlite3.Error as e:
            print(f"Error closing the connection: {e}")