# db
import os
import sqlite3
from src.model import my_file_model


MY_FILES_TABLE = 'files_store'

class DataBase:
    """
    This class knows how to work with Data Base based on SQL:
     1. create (open) the DB
     2. insert
     3. read back
     4. close DB
    """   
    def __init__(self, db_name: str) -> None:
        """
        create the connection, and the obj that will hold a connection to SQLite database.
        name of the data base will need to be given by user
        :param db_name: str
        """
        
        print("\n\nInitiation of the data base ... started")
        self.connection = None
        self.cursor = None       
        
        # remove the database file from the memory - if it exists, else the table will be growing each run of app
        os.remove(db_name) 

        print(f"Connecting to SQLITE3 data base, data base based on SQLite3, in-memory SQLite for testing: {db_name}")
        self.connection = sqlite3.connect(db_name) # create the connection to the sqlite3 DB        
        
        print(f"Creating cursor (based on connection to the data base), cursor will hold the table, using cursor the SQL QUERIES will be issued")
        self.cursor = self.connection.cursor()     # init of the cursor obj (that will hold the tbl), to execute SQL queries against the sqlite3 DB 
        self.create_table()
    

    def create_table(self) -> None:
        """
        # Define SQL query to create a table named 'files_storage'. The cursor will hold the table.
        Each record in the table will have then next columns:
        1.id
        2.source_file 
        3.date
        
        Each column has requirements
        exp: id must be integer type (it is Primary key for this table)
        """
        try:
            print("Executing SQL query to create a table ...")
            SQL_query = f'''
                        CREATE TABLE IF NOT EXISTS {MY_FILES_TABLE} 
                        (id INTEGER PRIMARY KEY,
                        source_file TEXT NOT NULL,
                        date TEXT NOT NULL)
                        '''            
            print(f"SQL query is: {SQL_query}")
            self.cursor.execute(SQL_query)
            # Execute the query and commit the transaction
            self.connection.commit()
            print(f"Creation of the table: {MY_FILES_TABLE} - Succedded")
        except sqlite3.Error as e:
            print(f"Creation of the table: {MY_FILES_TABLE} - Failed, error: {e}")        
            

    def insert(self, source_file: str, date: str) -> int:
        """
        This method is for inserting new record with fields: source_file, date into table 'files_store'
        :return the id of the newly inserted record
        """

        print("Executing SQL query to insert file into a table ...")
        try:
            self.cursor.execute(f'INSERT INTO {MY_FILES_TABLE} (source_file, date) VALUES (?, ?)',
                                (source_file, date))
            # commit the transaction
            self.connection.commit()
            # Fetch the autogenerated ID - the id of the newly inserted record
            return self.cursor.lastrowid
        except sqlite3.Error as e:
            print(f"Database error: {e}")
            return -1
    

    def get_all_files(self) -> list[my_file_model]:
        # execution of the query
        # query selects all records (files) from the table 'files_store'
        rows = []
        print("Executing SQL query to retrieve all files from a table ...")
        try:
            sql_query = f'SELECT * FROM {MY_FILES_TABLE}'
            print(f"SQL query is: {sql_query}")
            self.cursor.execute(sql_query)
            # we retrieve from a table raw records - each record is a file full name and date
            rows = self.cursor.fetchall()
            print(f"The number of received rows are: {len(rows)}")
        except sqlite3.Error as e:
            print(f"Database error: {e}")

        my_files = []
        # we need to create the -> file obj <- from the raw record. ConverFile extractuions may fail therefore it is surrounded with try and catch
        if not rows:
            print(f"No files could be found in the table {MY_FILES_TABLE}")
            # in this case will be returned             
        else:
            for row in rows:
                try:
                    # create file name obj from record from a table that is a raw data                    
                    # it says each raw will have: id, source_file,date
                    my_file = my_file_model(id=row[0],
                                            source_file=row[1],                                           
                                            date=row[2])
                    # store the records as a conversion objects
                    my_files.append(my_file)
                except Exception as e:
                    print(f"Error creating file object: {e}")
        return my_files
    

    def get_file_by_id(self, id: int) -> my_file_model:
        """
        This method receives id of the record in the table and retrieves a record 
        retrieve can fail if id isnt in the table
        :param id: an id of the desired record 
        :return: a record
        """
        print("Executing SQL query to retrieve a file from a table by id ...")
        entity = None
        try:
            sql_query = f'SELECT * FROM {MY_FILES_TABLE} WHERE id={id}'
            print(f"SQL query is: {sql_query}")
            self.cursor.execute(sql_query) 
            # raw data
            entity = self.cursor.fetchone()
            print(f"The received entity is: {entity}")
            if not entity:
                return None
        except sqlite3.Error as e:
            print(f"Database error: {e}")

        my_file = None
        try:
            # my_file from raw to my_file obj - here we do it for single record
            my_file = my_file_model( id=entity[0],
                                     source_file=entity[1],
                                     date=entity[2])
        except Exception as e:
            print(f"Error creating file object: {e}")
        finally:
            return my_file
        

    def close(self) -> None:
        """
        Closing the connection to resources
        :return: None
        """
        print(f"Closing connection to a table ...")
        try:
            self.connection.close()
        except sqlite3.Error as e:
            print(f"Error closing the connection: {e}")